name: my_portfolio
description: "My Work Experience"



version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  url_launcher:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
   - images/
   - screenshots/
   - screenshots/ask_ai/
   - screenshots/emi_calculator/
   - screenshots/table_clash/
   - screenshots/wordly/


